### ISSUE TITLE
:label: Beta Release changes

### ISSUE THREAD

**Issue by lnardon** [lnardon/Drucker#5]
Changes necessary for the beta release.

## Tasks

- [x] Add auth
- [x] Improve Entries table UI
- [x] Improve Project creation
- [x] Make DB changes update also on the app
- [x] Add Tag entity + interactions
- [x] Deploy docs + demo
